---
title: "circle"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{circle}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Authentication

To get started with Circle CI on Github, make sure to install the [Circle CI Github App](https://github.com/marketplace/circleci) and configure the "Free" plan for your account.

The first time any {circle} function is called, it will check for the existence of a Circle API key.
This API key is needed to securely talk to the Circle CI API and make requests.
There are two ways you can store the API key:
  - In `~/.circleci/cli.yml` via the following pattern
   
   ```yml
   host: https://circleci.com
   endpoint: graphql-unstable
   token: <token>
   ```
   
  - Via environment variable `R_CIRCLE` in `~/.Renviron` (recommended)

In addition, {circle} scrapes information about the current repository from Github.
To be able to do this, a `GITHUB_TOKEN` is needed.
You can create one using `usethis::browse_github_token()` if you haven't done so yet.

# Deployment

The easiest way to enable deployment from Circle CI builds to Github repositories is by using `use_circle_deploy()`:

```r
circle::use_circle_deploy()
✖ No 'user-key' found.
──────────────────────────────────────────────────────────────────────────────────────────────────
✔ Added a 'user key' to project '<repo-slug>' on Circle CI. 
This enables deployment from builds.
```

## Deployment keys

There two different types of keys on Circle CI: 

- Checkout keys

- SSH keys

### Checkout keys

Checkout keys are used to checkout your repository so that the build is starting.
If you've connected Circle CI to Github already, you will have a "deploy key" stored in every repository to be able to checkout the code.

However, this key does not have enough permissions to also deploy from builds.
To enable deployment, a "user-key" is needed. 
This key can be added using `use_circle_deploy()`.
This function will add a so called "user key" to the settings of the repo on Circle CI.
In addition, a SSH key with read/write permissions will be added to your Github profile under the "SSH and GPG keys" section with the title pointing to the respective repo.

### SSH keys

The private key will be added to your repo setting on Circle CI while the public key will be stored as a "deploy key" in your repository on Github.

---

If you do not want to use `use_circle_deploy()` and go the manual way of adding a SSH key to Circle CI, please be aware of [this issue](https://discuss.circleci.com/t/adding-ssh-keys-fails/7747).
